linters:
  enable-all: true
  disable:
    - tenv # Deprecated
    # Too noisy
    - exhaustruct
    - mnd
    - lll
    - varnamelen
    - funlen
    - cyclop
    - gocognit
    - err113
    - dupword
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
